### PR TITLE
transform: Add Woolworths Money

### PR DESCRIPTION
**Pull request by shenki**
Signed-off-by: Joel Stanley joel@jms.id.au

### CODE REVIEW

**Comment by amboar** [comment]
Thanks for taking the time to add Woolies support! One request though - there is a terrible tests file at `lib/tests/__init__.py` that contains a class exercising a bunch of the CSV sensing paths (`class TransformTest`). Do you mind adding some unit tests to it for this new format?

**Comment by shenki** [comment]
`make check` doesn't seem to do much. How do I run the tests?

I couldn't decypher what the `test_transform_$bank` tests were doing, so I didn't write one of those.

**Comment by shenki** [comment]
The travis script had the hint that I needed to run nosetests. Is there any reason we don't run that command as part of `make check`?

**Comment by amboar** [comment]
Thanks! BTW I've updated the `Makefile` to run `nosetests` in the `check` target in #18.

**Pull request merged**
